### ISSUE TITLE
Clarification regarding collection functions

### ISSUE THREAD

**Issue by area** [neo4j/cypher-refcard#16]
I lost an embarrassing amount of time earlier this week due to the following paragraph under collection functions:

> head({coll}), last({coll}), tail({coll})
> head returns the first, last the last element of the collection. tail the remainder of the collection. All return null for an empty collection.

I understood this to mean that `tail` returned everything that was not the first or last element of the collection, without really stopping to think about why a function might be called 'tail'. Rewording it to something along the lines of

> head({coll}), last({coll}), tail({coll})
> head returns the first, last the last element of the collection. tail returns all elements of the collection that are not the head. All return null for an empty collection.

would make it clearer.

**Comment by nawroth** [comment]
Thanks for the input! I'm reusing the wording from the manual to improve it: https://github.com/neo4j/neo4j/pull/5098
